CREATE DATABASE testdb;
CREATE ROLE "testuser" WITH CREATEDB LOGIN PASSWORD 'testuser';
REVOKE ALL PRIVILEGES ON SCHEMA public FROM public;
GRANT ALL PRIVILEGES ON DATABASE testdb TO testuser;
GRANT ALL PRIVILEGES ON SCHEMA public TO testuser;
