/* eslint-disable */

// Code generated by YAML8n and covered under the
// Candid Public License; DO NOT EDIT.

export type ISO639Code = string;

export interface Translation {
	[key: ISO639Code]: string,
}

export const ISO639Codes: {
	[key: ISO639Code]: string,
} = {
	ar: "عربي",
	de: "Deutsch",
	en: "English",
	es: "Español",
	fr: "Francais",
	hi: "हिन्दी",
	nl: "Nederlands",
	zh: "中文",
};

export function Translate (c: ISO639Code, t: Translation): string {
	const code = c.split("-")[0];
	if (t[code] !== undefined) {
		return t[code];
	}

	return t["en"];
}

export const ActionAdd: Translation = {
	ar: `يضيف`,
	de: `Hinzufügen`,
	en: `Add`,
	es: `Agregar`,
	fr: `Ajouter`,
	hi: `जोड़ना`,
	nl: `Toevoegen`,
	zh: `添加`,
};

export const ActionCancel: Translation = {
	ar: `يلغي`,
	de: `Stornieren`,
	en: `Cancel`,
	es: `Cancelar`,
	fr: `Annuler`,
	hi: `रद्द करना`,
	nl: `Annuleren`,
	zh: `取消`,
};

export const ActionClose: Translation = {
	ar: `يغلق`,
	de: `Schließen`,
	en: `Close`,
	es: `Cerca`,
	fr: `Fermer`,
	hi: `बंद करना`,
	nl: `Sluiten`,
	zh: `关闭`,
};

export const ActionConfirm: Translation = {
	ar: `يتأكد`,
	de: `Bestätigen`,
	en: `Confirm`,
	es: `Confirmar`,
	fr: `Confirmer`,
	hi: `पुष्टि करना`,
	nl: `Bevestigen`,
	zh: `确认`,
};

export const ActionDelete: Translation = {
	ar: `يمسح`,
	de: `Löschen`,
	en: `Delete`,
	es: `Borrar`,
	fr: `Supprimer`,
	hi: `मिटाना`,
	nl: `Verwijderen`,
	zh: `删除`,
};

export const ActionDeleteConfirm: Translation = {
	ar: `تأكيد الحذف`,
	de: `Löschen bestätigen`,
	en: `Confirm Delete`,
	es: `Confirmar eliminación`,
	fr: `Confirmation de la suppression`,
	hi: `हटाने की पुष्टि करें`,
	nl: `Verwijderen bevestigen`,
	zh: `确认删除`,
};

export const ActionDeselectAll: Translation = {
	ar: `الغاء تحديد الكل`,
	de: `Alle abwählen`,
	en: `Deselect All`,
	es: `Deseleccionar todo`,
	fr: `Tout déselectionner`,
	hi: `सबको अचयनित करो`,
	nl: `Alles deselecteren`,
	zh: `取消全选`,
};

export const ActionDismiss: Translation = {
	ar: `رفض`,
	de: `Verwerfen`,
	en: `Dismiss`,
	es: `Despedir`,
	fr: `Rejeter`,
	hi: `नकार देना`,
	nl: `Afwijzen`,
	zh: `解雇`,
};

export const ActionEdit: Translation = {
	ar: `يحرر`,
	de: `Bearbeiten`,
	en: `Edit`,
	es: `Editar`,
	fr: `Modifier`,
	hi: `संपादन करना`,
	nl: `Bewerken`,
	zh: `编辑`,
};

export const ActionImport: Translation = {
	ar: `يستورد`,
	de: `Importieren`,
	en: `Import`,
	es: `Importar`,
	fr: `Importer`,
	hi: `आयात`,
	nl: `Importeren`,
	zh: `进口`,
};

export const ActionKeepAwake: Translation = {
	ar: `ابقى يقظا`,
	de: `Bleib wach`,
	en: `Keep Awake`,
	es: `Mantenerse despierto`,
	fr: `Reste éveillé`,
	hi: `जागते रहना`,
	nl: `Wakker houden`,
	zh: `保持清醒`,
};

export const ActionNew: Translation = {
	ar: `جديد`,
	de: `Neu`,
	en: `New`,
	es: `Nuevo`,
	fr: `Nouveau`,
	hi: `नया`,
	nl: `Nieuw`,
	zh: `新的`,
};

export const ActionNone: Translation = {
	ar: `لا أحد`,
	de: `Keiner`,
	en: `None`,
	es: `Ninguno`,
	fr: `Aucun`,
	hi: `कोई नहीं`,
	nl: `Geen`,
	zh: `没有任何`,
};

export const ActionPreview: Translation = {
	ar: `معاينة`,
	de: `Vorschau`,
	en: `Preview`,
	es: `Avance`,
	fr: `Aperçu`,
	hi: `पूर्व दर्शन`,
	nl: `Voorbeeld`,
	zh: `预览`,
};

export const ActionSearch: Translation = {
	ar: `يبحث`,
	de: `Suchen`,
	en: `Search`,
	es: `Buscar`,
	fr: `Recherche`,
	hi: `खोज`,
	nl: `Zoeken`,
	zh: `搜索`,
};

export const ActionShow: Translation = {
	ar: `يعرض`,
	de: `Zeigen`,
	en: `Show`,
	es: `Espectáculo`,
	fr: `Montrer`,
	hi: `दिखाना`,
	nl: `Tonen`,
	zh: `展示`,
};

export const ActionUpdate: Translation = {
	ar: `تحديث`,
	de: `Aktualisieren`,
	en: `Update`,
	es: `Actualizar`,
	fr: `Mise à jour`,
	hi: `अद्यतन`,
	nl: `Update`,
	zh: `更新`,
};

export const ActionView: Translation = {
	ar: `منظر`,
	de: `Ansehen`,
	en: `View`,
	es: `Vista`,
	fr: `Voir`,
	hi: `देखना`,
	nl: `Weergave`,
	zh: `看法`,
};

export const AlertNewVersion: Translation = {
	ar: `نسخة جديدة متاحة`,
	de: `Neue Version ist verfügbar`,
	en: `New version is available`,
	es: `La nueva versión está disponible`,
	fr: `Une nouvelle version est disponible`,
	hi: `नया संस्करण उपलब्ध है`,
	nl: `Nieuwe versie is beschikbaar`,
	zh: `新版本可用`,
};

export const AppToolbarActionsOnThisPage: Translation = {
	ar: `على هذه الصفحة`,
	de: `Auf dieser Seite`,
	en: `On This Page`,
	es: `En esta página`,
	fr: `Sur cette page`,
	hi: `इस पृष्ठ पर`,
	nl: `Op deze pagina`,
	zh: `在本页`,
};

export const ColorBlack: Translation = {
	ar: `أسود`,
	de: `Schwarz`,
	en: `Black`,
	es: `Negro`,
	fr: `Noir`,
	hi: `काला`,
	nl: `Zwart`,
	zh: `黑色的`,
};

export const ColorBlue: Translation = {
	ar: `أزرق`,
	de: `Blau`,
	en: `Blue`,
	es: `Azul`,
	fr: `Bleu`,
	hi: `नीला`,
	nl: `Blauw`,
	zh: `蓝色的`,
};

export const ColorBrown: Translation = {
	ar: `بني`,
	de: `Braun`,
	en: `Brown`,
	es: `Marrón`,
	fr: `Brun`,
	hi: `भूरा`,
	nl: `Bruin`,
	zh: `棕色的`,
};

export const ColorGray: Translation = {
	ar: `رمادي`,
	de: `Grau`,
	en: `Gray`,
	es: `Gris`,
	fr: `Gris`,
	hi: `स्लेटी`,
	nl: `Grijs`,
	zh: `灰色的`,
};

export const ColorGreen: Translation = {
	ar: `أخضر`,
	de: `Grün`,
	en: `Green`,
	es: `Verde`,
	fr: `Vert`,
	hi: `हरा`,
	nl: `Groente`,
	zh: `绿色的`,
};

export const ColorIndigo: Translation = {
	ar: `نيلي`,
	de: `Indigo`,
	en: `Indigo`,
	es: `Índigo`,
	fr: `Indigo`,
	hi: `नील`,
	nl: `Indigo`,
	zh: `靛青`,
};

export const ColorOrange: Translation = {
	ar: `البرتقالي`,
	de: `Orange`,
	en: `Orange`,
	es: `Naranja`,
	fr: `Orange`,
	hi: `नारंगी`,
	nl: `Oranje`,
	zh: `橙子`,
};

export const ColorPink: Translation = {
	ar: `لون القرنفل`,
	de: `Rosa`,
	en: `Pink`,
	es: `Rosa`,
	fr: `Rose`,
	hi: `गुलाबी`,
	nl: `Roze`,
	zh: `粉色的`,
};

export const ColorPurple: Translation = {
	ar: `أرجواني`,
	de: `Lila`,
	en: `Purple`,
	es: `Púrpura`,
	fr: `Violet`,
	hi: `बैंगनी`,
	nl: `Paars`,
	zh: `紫色的`,
};

export const ColorRed: Translation = {
	ar: `أحمر`,
	de: `Rot`,
	en: `Red`,
	es: `Rojo`,
	fr: `Rouge`,
	hi: `लाल`,
	nl: `Rood`,
	zh: `红色的`,
};

export const ColorTeal: Translation = {
	ar: `بط نهري صغير`,
	de: `Blaugrün`,
	en: `Teal`,
	es: `verde azulado`,
	fr: `Sarcelle`,
	hi: `टील`,
	nl: `Teal`,
	zh: `蓝绿色`,
};

export const ColorWhite: Translation = {
	ar: `أبيض`,
	de: `Weiss`,
	en: `White`,
	es: `Blanco`,
	fr: `Blanc`,
	hi: `सफ़ेद`,
	nl: `Wit`,
	zh: `白色的`,
};

export const ColorYellow: Translation = {
	ar: `أصفر`,
	de: `Gelb`,
	en: `Yellow`,
	es: `Amarillo`,
	fr: `Jaune`,
	hi: `पीला`,
	nl: `Geel`,
	zh: `黄色的`,
};

export const Default: Translation = {
	ar: `تقصير`,
	de: `Standard`,
	en: `Default`,
	es: `Por defecto`,
	fr: `Défaut`,
	hi: `गलती करना`,
	nl: `Standaard`,
	zh: `默认`,
};

export const FormCreated: Translation = {
	ar: `مخلوق`,
	de: `Erstellt`,
	en: `Created`,
	es: `Creado`,
	fr: `Créé`,
	hi: `बनाया था`,
	nl: `Gemaakt`,
	zh: `已创建`,
};

export const FormImageSelect: Translation = {
	ar: `يختار`,
	de: `Wählen`,
	en: `Select`,
	es: `Seleccionar`,
	fr: `Sélectionner`,
	hi: `चुनना`,
	nl: `Selecteer`,
	zh: `选择`,
};

export const FormImportCSVField: Translation = {
	ar: `تعيين حقل CSV`,
	de: `CSV-Feldzuordnung`,
	en: `CSV Field Mapping`,
	es: `Asignación de campos CSV`,
	fr: `Cartographie des champs CSV`,
	hi: `सीएसवी फील्ड मैपिंग`,
	nl: `CSV-veldtoewijzing`,
	zh: `CSV 字段映射`,
};

export const FormImportCSVSelectCSV: Translation = {
	ar: `حدد CSV`,
	de: `Wählen Sie CSV-Datei aus`,
	en: `Select CSV`,
	es: `Seleccionar CSV`,
	fr: `Sélectionnez CSV`,
	hi: `सीएसवी का चयन करें`,
	nl: `Selecteer CSV`,
	zh: `选择 CSV`,
};

export const FormImportCSVTooltip: Translation = {
	ar: `الخصائص المراد استخدامها لتصفية عناصر المخزون`,
	de: `Eigenschaften zum Filtern von Inventarelementen`,
	en: `Properties to use for filtering inventory items`,
	es: `Propiedades a usar para filtrar artículos de inventario`,
	fr: `Propriétés à utiliser pour filtrer les éléments d'inventaire`,
	hi: `इन्वेंट्री आइटम को फ़िल्टर करने के लिए उपयोग करने के लिए गुण`,
	nl: `Eigenschappen om te gebruiken voor het filteren van inventarisitems`,
	zh: `用于过滤库存项目的属性`,
};

export const FormItemDurationHour: Translation = {
	ar: `ساعة`,
	de: `Stunde`,
	en: `Hour`,
	es: `Hora`,
	fr: `Heure`,
	hi: `घंटा`,
	nl: `Uur`,
	zh: `小时`,
};

export const FormItemDurationHours: Translation = {
	ar: `ساعات`,
	de: `Std`,
	en: `Hours`,
	es: `Horas`,
	fr: `Heures`,
	hi: `घंटे`,
	nl: `Uur`,
	zh: `小时`,
};

export const FormItemDurationMinute: Translation = {
	ar: `دقيقة`,
	de: `Minute`,
	en: `Minute`,
	es: `Minuto`,
	fr: `Minute`,
	hi: `मिनट`,
	nl: `Minuut`,
	zh: `分钟`,
};

export const FormItemDurationMinutes: Translation = {
	ar: `دقائق`,
	de: `Protokoll`,
	en: `Minutes`,
	es: `Minutos`,
	fr: `Minutes`,
	hi: `मिनट`,
	nl: `Minuten`,
	zh: `分钟`,
};

export const FormItemInputIconName: Translation = {
	ar: `أيقونة`,
	de: `Symbol`,
	en: `Icon`,
	es: `Icono`,
	fr: `Icône`,
	hi: `आइकन`,
	nl: `Icoon`,
	zh: `图标`,
};

export const FormItemInputIconTooltip: Translation = {
	ar: `يتم عرض الرمز مع العنصر. استخدم هذا الارتباط للبحث عن الرموز الموجودة على`,
	de: `Symbol, das mit dem Element angezeigt werden soll. Verwenden Sie diesen Link, um nach Symbolen zu suchen`,
	en: `Icon to be displayed with the item.  Use this link to search for icons on`,
	es: `Icono que se mostrará con el elemento. Utilice este enlace para buscar iconos en`,
	fr: `Icône à afficher avec l'élément. Utilisez ce lien pour rechercher des icônes sur`,
	hi: `आइटम के साथ प्रदर्शित किया जाने वाला चिह्न। आइकन खोजने के लिए इस लिंक का उपयोग करें`,
	nl: `Icoon dat bij het item moet worden weergegeven. Gebruik deze link om iconen op te zoeken`,
	zh: `与项目一起显示的图标。使用此链接搜索图标`,
};

export const FormItemNewPasswordPassword: Translation = {
	ar: `كلمة المرور`,
	de: `Passwort`,
	en: `Password`,
	es: `Contraseña`,
	fr: `Mot de passe`,
	hi: `पासवर्ड`,
	nl: `Wachtwoord`,
	zh: `密码`,
};

export const FormItemNewPasswordTooltip: Translation = {
	ar: `ثمانية أحرف على الأقل`,
	de: `Mindestens acht Zeichen`,
	en: `Minimum eight characters`,
	es: `Mínimo ocho caracteres`,
	fr: `Minimum huit caractères`,
	hi: `न्यूनतम आठ वर्ण`,
	nl: `Minimaal acht tekens`,
	zh: `至少八个字符`,
};

export const FormItemSelectColorName: Translation = {
	ar: `لون`,
	de: `Farbe`,
	en: `Color`,
	es: `Color`,
	fr: `Couleur`,
	hi: `रंग`,
	nl: `Kleur`,
	zh: `颜色`,
};

export const FormItemSelectColorTooltip: Translation = {
	ar: `ما اللون الذي يجب استخدامه`,
	de: `Welche Farbe zu verwenden`,
	en: `What color to use`,
	es: `Que color usar`,
	fr: `Quelle couleur utiliser`,
	hi: `किस रंग का प्रयोग करें`,
	nl: `Welke kleur te gebruiken`,
	zh: `使用什么颜色`,
};

export const FormItemSelectCurrencyFormat: Translation = {
	ar: `تنسيق العملة`,
	de: `Währungsformat`,
	en: `Currency Format`,
	es: `Formato de moneda`,
	fr: `Format de devise`,
	hi: `मुद्रा प्रारूप`,
	nl: `Valuta Formaat`,
	zh: `货币格式`,
};

export const FormItemSelectCurrencyFormatTooltip: Translation = {
	ar: `تنسيق العرض للعملات`,
	de: `Anzeigeformat für Währungen`,
	en: `Display format for currencies`,
	es: `Formato de visualización para monedas`,
	fr: `Format d'affichage des devises`,
	hi: `मुद्राओं के लिए प्रदर्शन प्रारूप`,
	nl: `Weergaveformaat voor valuta`,
	zh: `货币显示格式`,
};

export const FormItemTextAreaScanText: Translation = {
	ar: `مسح النص من الصورة`,
	de: `Text aus Bild scannen`,
	en: `Scan Text From Picture`,
	es: `Escanear texto de la imagen`,
	fr: `Numériser le texte à partir de l'image`,
	hi: `चित्र से टेक्स्ट स्कैन करें`,
	nl: `Scan tekst van afbeelding`,
	zh: `从图片中扫描文本`,
};

export const FormLastUpdated: Translation = {
	ar: `آخر تحديث`,
	de: `Letzte Aktualisierung`,
	en: `Last Updated`,
	es: `Última actualización`,
	fr: `Dernière mise à jour`,
	hi: `आखरी अपडेट`,
	nl: `Laatst bijgewerkt`,
	zh: `最近更新时间`,
};

export const FormRecurrenceDays: Translation = {
	ar: `أيام`,
	de: `Tage`,
	en: `Days`,
	es: `Días`,
	fr: `Jours`,
	hi: `दिन`,
	nl: `Dagen`,
	zh: `天`,
};

export const FormRecurrenceEnd: Translation = {
	ar: `إنهاء التكرار في`,
	de: `Wiederholung beenden ein`,
	en: `End Recurrence On`,
	es: `Terminar recurrencia en`,
	fr: `Fin de la récurrence le`,
	hi: `पुनरावृत्ति समाप्त करें`,
	nl: `Einde herhaling op`,
	zh: `结束循环`,
};

export const FormRecurrenceEndTooltip: Translation = {
	ar: `متى تتوقف عن التكرار`,
	de: `Wann aufhören, sich zu wiederholen`,
	en: `When to stop recurring`,
	es: `Cuándo dejar de repetirse`,
	fr: `Quand arrêter de se reproduire`,
	hi: `आवर्ती कब बंद करें`,
	nl: `Wanneer stoppen met herhalen`,
	zh: `什么时候停止重复`,
};

export const FormRecurrenceFirst: Translation = {
	ar: `أولاً`,
	de: `Erste`,
	en: `First`,
	es: `Primero`,
	fr: `D'abord`,
	hi: `पहला`,
	nl: `Eerst`,
	zh: `第一的`,
};

export const FormRecurrenceFourth: Translation = {
	ar: `الرابعة`,
	de: `Vierte`,
	en: `Fourth`,
	es: `Cuatro`,
	fr: `Quatrième`,
	hi: `चौथी`,
	nl: `Vierde`,
	zh: `第四`,
};

export const FormRecurrenceFourthToLast: Translation = {
	ar: `الرابع إلى الأخير`,
	de: `Vierter bis letzter`,
	en: `Fourth To Last`,
	es: `Cuarto al último`,
	fr: `Quatrième avant dernier`,
	hi: `चौथा से अंतिम`,
	nl: `Vierde tot laatste`,
	zh: `倒数第四`,
};

export const FormRecurrenceLabel: Translation = {
	ar: `تكرار كل...`,
	de: `Wiederhole jeden...`,
	en: `Repeat every...`,
	es: `Repite cada...`,
	fr: `Répétez chaque...`,
	hi: `हर बार दोहराएं...`,
	nl: `Herhaal elke...`,
	zh: `重复每...`,
};

export const FormRecurrenceLast: Translation = {
	ar: `آخر`,
	de: `Zuletzt`,
	en: `Last`,
	es: `Último`,
	fr: `Dernier`,
	hi: `अंतिम`,
	nl: `Laatste`,
	zh: `最后的`,
};

export const FormRecurrenceMonths: Translation = {
	ar: `شهور`,
	de: `Monate`,
	en: `Months`,
	es: `Meses`,
	fr: `Mois`,
	hi: `महीने`,
	nl: `Maanden`,
	zh: `月`,
};

export const FormRecurrenceNextDate: Translation = {
	ar: `التاريخ القادم`,
	de: `Nächstes Datum`,
	en: `Next Date`,
	es: `Proxima fecha`,
	fr: `Prochain rendez-vous`,
	hi: `अगली तारीख`,
	nl: `Volgende datum`,
	zh: `下一个日期`,
};

export const FormRecurrenceSecond: Translation = {
	ar: `ثانية`,
	de: `Zweite`,
	en: `Second`,
	es: `Segundo`,
	fr: `Deuxième`,
	hi: `दूसरा`,
	nl: `Seconde`,
	zh: `第二`,
};

export const FormRecurrenceSecondToLast: Translation = {
	ar: `من الثاني إلى الأخير`,
	de: `Vorletzte`,
	en: `Second To Last`,
	es: `Penúltimo`,
	fr: `Avant-dernier`,
	hi: `आखरी से पहले`,
	nl: `Voorlaatste`,
	zh: `倒数第二`,
};

export const FormRecurrenceSpecificDate: Translation = {
	ar: `تاريخ معين`,
	de: `Bestimmtes Datum`,
	en: `Specific Date`,
	es: `Fecha específica`,
	fr: `Date spécifique`,
	hi: `विशिष्ट तारीख`,
	nl: `Specifieke datum`,
	zh: `具体日期`,
};

export const FormRecurrenceThird: Translation = {
	ar: `ثالث`,
	de: `Dritte`,
	en: `Third`,
	es: `Tercero`,
	fr: `Troisième`,
	hi: `तीसरा`,
	nl: `Derde`,
	zh: `第三`,
};

export const FormRecurrenceThirdToLast: Translation = {
	ar: `الثالث إلى الأخير`,
	de: `Drittletzter`,
	en: `Third To Last`,
	es: `antepenúltimo`,
	fr: `Avant-dernier`,
	hi: `थर्ड टू लास्ट`,
	nl: `Derde tot laatste`,
	zh: `倒数第三`,
};

export const FormRecurrenceTooltip: Translation = {
	ar: `قم بإنشاء التكرار ليوم أو أسبوع أو شهر أو تاريخ محدد`,
	de: `Erstellen Sie die Wiederholung für einen bestimmten Tag, eine Woche, einen Monat oder ein Datum`,
	en: `Create the recurrence for a specific day, week, month, or date`,
	es: `Crear la recurrencia para un día, semana, mes o fecha específicos`,
	fr: `Créer la récurrence pour un jour, une semaine, un mois ou une date spécifique`,
	hi: `किसी विशिष्ट दिन, सप्ताह, माह या दिनांक के लिए पुनरावृत्ति बनाएँ`,
	nl: `Maak de herhaling voor een specifieke dag, week, maand of datum`,
	zh: `为特定的一天、一周、一个月或日期创建重复`,
};

export const FormRecurrenceWeeks: Translation = {
	ar: `أسابيع`,
	de: `Wochen`,
	en: `Weeks`,
	es: `Semanas`,
	fr: `Semaines`,
	hi: `हफ्तों`,
	nl: `Weken`,
	zh: `周`,
};

export const FormRecurrenceYears: Translation = {
	ar: `سنين`,
	de: `Jahre`,
	en: `Years`,
	es: `Años`,
	fr: `Années`,
	hi: `साल`,
	nl: `Jaren`,
	zh: `年`,
};

export const Help: Translation = {
	ar: `يساعد`,
	de: `Hilfe`,
	en: `Help`,
	es: `Ayuda`,
	fr: `Aider`,
	hi: `मदद`,
	nl: `Hulp`,
	zh: `帮助`,
};

export const NoImage: Translation = {
	ar: `لا توجد صورة`,
	de: `Kein Bild`,
	en: `No Image`,
	es: `Sin imágen`,
	fr: `Pas d'image`,
	hi: `चित्र उपलब्द नहीं है`,
	nl: `Geen afbeelding`,
	zh: `没有图像`,
};

export const Or: Translation = {
	ar: `أو`,
	de: `Oder`,
	en: `Or`,
	es: `O`,
	fr: `Ou`,
	hi: `या`,
	nl: `Of`,
	zh: `或者`,
};

export const TableHeaderFilterTooltip: Translation = {
	ar: `قم بتصفية القيم في هذا العمود. يمكن أن يكون هذا عبارة عن سلسلة بسيطة أو تعبيرًا عاديًا (RegExp).`,
	de: `Filtern Sie die Werte in dieser Spalte. Dies kann ein einfacher String oder ein regulärer Ausdruck (RegExp) sein.`,
	en: `Filter the values in this column.  This can be a simple string or a regular expression (RegExp).`,
	es: `Filtre los valores en esta columna. Puede ser una cadena simple o una expresión regular (RegExp).`,
	fr: `Filtrez les valeurs dans cette colonne. Il peut s'agir d'une simple chaîne ou d'une expression régulière (RegExp).`,
	hi: `इस कॉलम में मानों को फ़िल्टर करें। यह एक साधारण स्ट्रिंग या रेगुलर एक्सप्रेशन (RegExp) हो सकता है।`,
	nl: `Filter de waarden in deze kolom. Dit kan een eenvoudige string zijn of een reguliere expressie (RegExp).`,
	zh: `过滤此列中的值。这可以是简单的字符串或正则表达式 (RegExp)。`,
};

export const TableNothing: Translation = {
	ar: `لم يتم العثور على شيء`,
	de: `Nichts gefunden`,
	en: `Nothing Found`,
	es: `Nada Encontrado`,
	fr: `rien n'a été trouvé`,
	hi: `कुछ भी नहीं मिला`,
	nl: `Niets gevonden`,
	zh: `什么都没找到`,
};

export const TableShowColumns: Translation = {
	ar: `إظهار الأعمدة`,
	de: `Spalten anzeigen`,
	en: `Show Columns`,
	es: `Mostrar columnas`,
	fr: `Afficher les colonnes`,
	hi: `कॉलम दिखाएं`,
	nl: `Kolommen tonen`,
	zh: `显示列`,
};

export const TooltipMarkdown: Translation = {
	ar: `يستخدم هذا الإدخال Markdown`,
	de: `Diese Eingabe verwendet Markdown`,
	en: `This input uses Markdown`,
	es: `Esta entrada usa Markdown`,
	fr: `Cette entrée utilise Markdown`,
	hi: `यह इनपुट मार्कडाउन का उपयोग करता है`,
	nl: `Deze invoer gebruikt Markdown`,
	zh: `此输入使用 Markdown`,
};

export const WeekdayFriday: Translation = {
	ar: `جمعة`,
	de: `Freitag`,
	en: `Friday`,
	es: `Viernes`,
	fr: `Vendredi`,
	hi: `शुक्रवार`,
	nl: `Vrijdag`,
	zh: `星期五`,
};

export const WeekdayMonday: Translation = {
	ar: `الاثنين`,
	de: `Montag`,
	en: `Monday`,
	es: `Lunes`,
	fr: `Lundi`,
	hi: `सोमवार`,
	nl: `Maandag`,
	zh: `周一`,
};

export const WeekdaySaturday: Translation = {
	ar: `السبت`,
	de: `Samstag`,
	en: `Saturday`,
	es: `Sábado`,
	fr: `Samedi`,
	hi: `शनिवार`,
	nl: `Zaterdag`,
	zh: `周六`,
};

export const WeekdaySunday: Translation = {
	ar: `الأحد`,
	de: `Sonntag`,
	en: `Sunday`,
	es: `Domingo`,
	fr: `Dimanche`,
	hi: `रविवार`,
	nl: `Zondag`,
	zh: `星期日`,
};

export const WeekdayThursday: Translation = {
	ar: `يوم الخميس`,
	de: `Donnerstag`,
	en: `Thursday`,
	es: `Jueves`,
	fr: `Jeudi`,
	hi: `गुरुवार`,
	nl: `Donderdag`,
	zh: `周四`,
};

export const WeekdayTuesday: Translation = {
	ar: `يوم الثلاثاء`,
	de: `Dienstag`,
	en: `Tuesday`,
	es: `Martes`,
	fr: `Mardi`,
	hi: `मंगलवार`,
	nl: `Dinsdag`,
	zh: `周二`,
};

export const WeekdayWednesday: Translation = {
	ar: `الأربعاء`,
	de: `Mittwoch`,
	en: `Wednesday`,
	es: `Miércoles`,
	fr: `Mercredi`,
	hi: `बुधवार`,
	nl: `Woensdag`,
	zh: `周三`,
};
